import { Injectable, Logger } from '@nestjs/common';

import { metrics } from '../../base';

/**
 * AI Cost Observability Service
 *
 * Tracks AI provider usage metrics via OpenTelemetry for dashboarding and alerting.
 * Emits metrics with dimensions: provider, model, feature, user_tier.
 *
 * Metrics emitted:
 * - copilot.tokens.input: Input tokens consumed
 * - copilot.tokens.output: Output tokens generated
 * - copilot.cost.estimated: Estimated cost in USD (millicents for precision)
 * - copilot.request.duration: Request duration in ms
 * - copilot.request.count: Total request count
 * - copilot.request.errors: Error count
 * - copilot.circuit_breaker.state: Circuit breaker state changes
 */

// Approximate cost per 1K tokens (in USD millicents) — update as pricing changes
const TOKEN_COSTS: Record<string, { input: number; output: number }> = {
  'gpt-4o': { input: 250, output: 1000 },
  'gpt-4o-2024-08-06': { input: 250, output: 1000 },
  'gpt-5-mini': { input: 15, output: 60 },
  'claude-sonnet-4-5@20250929': { input: 300, output: 1500 },
  'claude-opus-4-6': { input: 1500, output: 7500 },
  'gemini-2.5-flash': { input: 15, output: 60 },
  'gemini-embedding-001': { input: 1, output: 0 },
  'gpt-image-1': { input: 500, output: 0 },
  default: { input: 100, output: 400 },
};

export interface CopilotUsageEvent {
  provider: string;
  model: string;
  feature: string;
  userId?: string;
  workspaceId?: string;
  inputTokens: number;
  outputTokens: number;
  durationMs: number;
  success: boolean;
  errorType?: string;
}

@Injectable()
export class CopilotMetricsService {
  private readonly logger = new Logger(CopilotMetricsService.name);

  /**
   * Record a copilot API call with full cost and performance metrics.
   */
  recordUsage(event: CopilotUsageEvent): void {
    const labels = {
      provider: event.provider,
      model: event.model,
      feature: event.feature,
    };

    // Token counts
    metrics.copilot
      .counter('tokens_input', {
        description: 'Input tokens consumed by AI provider',
      })
      .add(event.inputTokens, labels);

    metrics.copilot
      .counter('tokens_output', {
        description: 'Output tokens generated by AI provider',
      })
      .add(event.outputTokens, labels);

    // Estimated cost
    const costPerK = TOKEN_COSTS[event.model] ?? TOKEN_COSTS.default;
    const estimatedCostMillicents =
      (event.inputTokens / 1000) * costPerK.input +
      (event.outputTokens / 1000) * costPerK.output;

    metrics.copilot
      .counter('cost_estimated_millicents', {
        description: 'Estimated cost in USD millicents',
      })
      .add(Math.round(estimatedCostMillicents), labels);

    // Duration
    metrics.copilot
      .histogram('request_duration_ms', {
        description: 'AI provider request duration in milliseconds',
      })
      .record(event.durationMs, labels);

    // Request count
    metrics.copilot
      .counter('request_count', {
        description: 'Total AI provider request count',
      })
      .add(1, labels);

    // Error tracking
    if (!event.success) {
      metrics.copilot
        .counter('request_errors', {
          description: 'AI provider request error count',
        })
        .add(1, {
          ...labels,
          error_type: event.errorType ?? 'unknown',
        });
    }
  }

  /**
   * Record a circuit breaker state change.
   */
  recordCircuitBreakerChange(
    provider: string,
    oldState: string,
    newState: string
  ): void {
    metrics.copilot
      .counter('circuit_breaker_transitions', {
        description: 'Circuit breaker state transitions',
      })
      .add(1, {
        provider,
        from_state: oldState,
        to_state: newState,
      });

    this.logger.log(
      `Circuit breaker [${provider}]: ${oldState} -> ${newState}`
    );
  }
}
